garbage_list = [ "|", "Full Audio", "Full Song", "Full Album", "Full Video", "Full Lyrics", 
    "()", "1" "(", ")", "[", "]", "{", "}", "lyrics", "lyric", "official", "video", "audio", 
    "music", "song", "ft.", "feat.", "feat", "ft", "featuring", "remix", "remastered", 
    "remaster", "hd", "hq", "4k", "8k", "live", "cover", "karaoke", "instrumental", 
    "version", "edit", "explicit", "clean", "radio", "mix", "single", "album", "track", 
    "performance", "concert", "clip", "visualizer", "mv", "official video", "official audio", 
    "music video", "lyric video", "teaser", "trailer", "premiere", "out now", "new", 
    "exclusive", "full", "original", "extended", "short", "intro", "outro", "vs", "vs.", 
    "x", "prod.", "produced by", "director", "dir.", "starring", "theme", "soundtrack", 
    "OST", "opening", "ending", "scene", "feature", "feat", "ft", "and", "with", "by", 
    "episode", "ep.", "chapter", "part", "officially", "recorded", "studio", "special", 
    "performance video", "fan-made", "reaction", "re-upload", "streaming", "digitally", 
    "unplugged", "cover art", "session", "tribute", "acoustic", "exclusive version", "Hit Songs",
    "Popular Songs", "Top Songs", "Top Hits", "Best Songs", "Best Hits", "Greatest Hits", "Moviebox",
]
